# Jekyll Configuration
title: "Your Name"
description: "Ideas, essays, and projects."
url: "https://your-domain.netlify.app"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Plugins
plugins:
  - jekyll-last-modified-at

# Exclude files from processing
exclude:
  - vendor/
  - node_modules/
  - .bundle/
  - .byebug_history
  - .DS_Store
  - .git/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .vscode/
  - README.md
  - netlify.toml
  - Gemfile
  - Gemfile.lock
  - _notes/  # Your cheat sheet notes

# Performance optimizations
incremental: true
profile: false
strict_front_matter: true

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false