# Netlify.toml - Optimized Jekyll Build Configuration

[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.2"
  # Suppress mise warnings
  MISE_DISABLE_TOOLS = "node,python,go,php"
  # Jekyll optimizations
  JEKYLL_ENV = "production"
  # Bundle optimizations
  BUNDLE_CACHE_PATH = "./vendor/bundle"
  BUNDLE_WITHOUT = "development:test"

# Cache optimization
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Faster builds with dependency caching
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Redirect rules (optional)
[[redirects]]
  from = "/notes/*"
  to = "/404"
  status = 404